//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MuCat.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      102
#define IDR_MAINFRAME                   128
#define IDR_MUCATTYPE                   129
#define IDD_BINDIALOG                   131
#define IDD_SPECDIALOG                  132
#define IDD_XRAY_DIALOG                 133
#define IDD_VIEWZOOM                    134
#define IDD_STOPDIALOG                  137
#define IDD_GAINDIALOG                  138
#define IDD_POSITIONDIALOG              139
#define IDD_DIMDIALOG                   140
#define IDD_MAGDIALOG                   141
#define IDD_PARAMETER_DURATION          143
#define IDD_GEOMETRYDIALOG              144
#define IDD_PAUSEDIALOG                 145
#define IDD_XRAYRESTART                 146
#define IDI_ICON1                       147
#define IDC_BINEDIT                     1002
#define IDC_BINSPIN                     1003
#define IDC_USER                        1005
#define IDC_OWNER                       1006
#define IDC_DESCRIPTION                 1007
#define IDC_COMMENT                     1008
#define IDC_FILTER                      1009
#define IDC_VOLTAGE                     1010
#define IDC_CURRENT                     1011
#define IDC_ISSUE                       1012
#define IDC_ZOOM25                      1015
#define IDC_ZOOM33                      1016
#define IDC_ZOOM50                      1017
#define IDC_ZOOM100                     1018
#define IDC_ZOOM200                     1019
#define IDC_ZOOM300                     1020
#define IDC_ZOOM400                     1021
#define IDC_GAINSPEED                   1027
#define IDC_GAINSPEEDSPIN               1029
#define IDC_GAINGAIN                    1030
#define IDC_GAINGAINSPIN                1034
#define IDC_GAINELECTRON                1035
#define IDC_ROTATIONSPIN                1037
#define IDC_ROTATION                    1038
#define IDC_DIMHEIGHT                   1039
#define IDC_DIMHEIGHTSPIN               1041
#define IDC_DIMLENGTH                   1042
#define IDC_DIMLENGTHSPIN               1043
#define IDC_PARAMETERMAG                1046
#define IDC_PARAMETER_DURATION          1047
#define IDC_PARAMETERDURATIONSPIN       1048
#define IDC_PARAMETERSTILL              1049
#define IDC_PARAMETERSTILLSPIN          1050
#define IDC_ELEVATION                   1052
#define IDC_TRANSLATION                 1053
#define IDC_ELEVATIONSPIN               1054
#define IDC_TRANSLATIONSPIN             1055
#define IDC_DIMPROJ                     1056
#define IDC_DIMPROJSPIN                 1057
#define IDC_DIMBLOCKS                   1058
#define IDC_DIMSHIFT                    1059
#define IDC_DIMBLOCKSSPIN               1061
#define IDC_DIMSHIFTSPIN                1062
#define IDC_EDITPEPPER                  1063
#define IDC_PEPPERCHECK                 1064
#define IDC_GEOMETRYPIXELSIZE           1065
#define IDC_GEOMETRYDISTANCE            1066
#define IDC_DIMMAXSLICES                1066
#define IDC_GEOMETRYGRADIENT            1067
#define IDC_CHECKPAUSE                  1068
#define IDC_KILLTHETA                   1069
#define IDC_KILLZ                       1070
#define IDC_POSDISTANCE                 1071
#define IDC_POSDISTANCESPIN             1073
#define IDC_POSITIONPIXELSIZE           1074
#define IDC_XRAYRESTART                 1075
#define IDC_DIMAV                       1076
#define IDC_DIMAVSPIN                   1077
#define IDC_CHECK1                      1078
#define IDC_WAIT45                      1078
#define ID_SCAN                         32771
#define ID_FOCUS                        32772
#define ID_STILL                        32773
#define ID_RECORD                       32774
#define ID_PARAMETER_BIN                32775
#define ID_MULTISCAN                    32776
#define ID_EDIT_SPEC                    32777
#define ID_EDIT_XRAY                    32778
#define ID_VIEW_ZOOM                    32779
#define ID_INITFOCUS                    32780
#define IDD_PARAMETER_GAIN              32781
#define ID_STOP                         32782
#define ID_BRIGHT_UP                    32787
#define ID_BRIGHT_DOWN                  32788
#define ID_CONTRAST_UP                  32790
#define ID_CONTRAST_DOWN                32791
#define ID_AUTOSCALE                    32792
#define ID_POSITION                     32793
#define ID_PARAMETER_DIM                32794
#define IDD_PARAMETER_SPEC              32795
#define ID_PARAMETER_MAG                32796
#define ID_PARAMETER_EXP                32797
#define IDC_EDIT_GEOMETRY               32798
#define ID_EDIT_GEOMETRY                32799
#define ID_BUTTONDIM                    32801
#define ID_BUTTONSHARPNESS              32802
#define ID_BUTTONCENTRE                 32803
#define ID_SHUTTERBUTTON                32807
#define ID_LOCATE_CAM_SOURCE            32808
#define ID_HOME                         32809
#define ID_BUTTON32812                  32812
#define ID_TDIFIX                       32812
#define ID_INDICATOR_PROJ               61447
#define ID_INDICATOR_TEMP               61448
#define ID_INDICATOR_CURSOR             61449
#define ID_INDICATOR_PEPPER             61450
#define ID_INDICATOR_DURATION           61451
#define ID_INDICATOR_MAX                61452
#define ID_INDICATOR_FIN                61453
#define ID_INDICATOR_BIN                61454
#define ID_INDICATOR_SHARP              61455

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
